<?php

class IconCart_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'icon_cart';
    protected $title = 'Case Shop Cart';
    protected $icon = 'eicon-cart-medium';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"style","label":"Style","type":"select","options":{"style-default":"Default","style-box":"Box"},"default":"style-default"},{"name":"icon_image_type","label":"Icon Image Type","type":"select","options":{"img":"Image","ic":"Icon"},"default":"ic"},{"name":"pxl_icon","label":"Icon","type":"icons","fa4compatibility":"icon","condition":{"icon_image_type":["ic"]}},{"name":"image","label":"Icon Image","type":"media","condition":{"icon_image_type":["img"]}},{"name":"icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-cart-sidebar-button i":"color: {{VALUE}};"},"condition":{"icon_image_type":["img"]}},{"name":"icon_color_hover","label":"Icon Color Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-cart-sidebar-button:hover i":"color: {{VALUE}};"},"condition":{"icon_image_type":["img"]}},{"name":"size","label":"Icon Size","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-cart-sidebar-button i":"font-size: {{SIZE}}{{UNIT}};"}},{"name":"gap","label":"Gap","type":"slider","control_type":"responsive","range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-cart":"gap: {{SIZE}}px;"}},{"name":"box_color","label":"Box Color","type":"color","selectors":{"{{WRAPPER}} .pxl-cart-sidebar-button":"background-color: {{VALUE}};"},"condition":{"style":["style-box"]}},{"name":"box_color_hv","label":"Box Color Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-cart-sidebar-button:hover":"background-color: {{VALUE}};"},"condition":{"style":["style-box"]}},{"name":"box_height","label":"Box Height","type":"slider","control_type":"responsive","size_units":["px"],"condition":{"style":["style-box"]},"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-cart-sidebar-button":"height: {{SIZE}}{{UNIT}};"}},{"name":"box_width","label":"Box Width","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-cart-sidebar-button":"width: {{SIZE}}{{UNIT}};"},"condition":{"style":["style-box"]}},{"name":"show_sub_total","label":"Show Sub Total","type":"switcher","default":"true","description":"Display outside site!"},{"name":"heading_subtotal","label":"Sub Total","type":"heading","separator":"before","condition":{"show_sub_total":"true"}},{"name":"subtotal_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-cart .pxl-sub--total":"color: {{VALUE}};"},"condition":{"show_sub_total":"true"}},{"name":"subtotal_typography","label":"Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-cart .pxl-sub--total","condition":{"show_sub_total":"true"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}